/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moise
 */
public class TelaTabelaDeDados extends javax.swing.JFrame {

    /**
     * Creates new form TelaTabelaDeDados
     */
    public TelaTabelaDeDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAvancar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        lbl_NameProcess = new javax.swing.JLabel();
        txt_NameProcess = new javax.swing.JTextField();
        lbl_BurstTime = new javax.swing.JLabel();
        txt_BurstTime = new javax.swing.JTextField();
        lbl_Priority = new javax.swing.JLabel();
        txt_Priority = new javax.swing.JTextField();
        BtEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaDeDados = new javax.swing.JTable();
        BtInserir = new javax.swing.JButton();
        lbl_ArrivalTime = new javax.swing.JLabel();
        txt_ArrivalTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtAvancar.setText("Avancar");
        BtAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAvancarActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        lbl_NameProcess.setText("Process");

        lbl_BurstTime.setText("Burst Time");

        txt_BurstTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BurstTimeActionPerformed(evt);
            }
        });

        lbl_Priority.setText("Priority");

        BtEditar.setText("Editar");
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });

        TabelaDeDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Process", "Arrival Time", "Burst Time", "Priority"
            }
        ));
        jScrollPane1.setViewportView(TabelaDeDados);

        BtInserir.setText("Inserir");
        BtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInserirActionPerformed(evt);
            }
        });

        lbl_ArrivalTime.setText("Arrival Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(BtCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_NameProcess)
                                    .addComponent(BtEditar)
                                    .addComponent(txt_NameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ArrivalTime)
                            .addComponent(txt_ArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtInserir)
                        .addComponent(BtAvancar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_BurstTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_BurstTime))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Priority)
                            .addComponent(txt_Priority, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Priority)
                    .addComponent(lbl_BurstTime)
                    .addComponent(lbl_ArrivalTime)
                    .addComponent(lbl_NameProcess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtInserir)
                            .addComponent(BtEditar))
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_BurstTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NameProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAvancar)
                    .addComponent(BtCancelar))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(169, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAvancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAvancarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        // TODO add your handling code here:

        txt_NameProcess.setText(TabelaDeDados.getValueAt(TabelaDeDados.getSelectedRow(), 0) + "");
        txt_ArrivalTime.setText(TabelaDeDados.getValueAt(TabelaDeDados.getSelectedRow(), 1) + "");
        txt_BurstTime.setText(TabelaDeDados.getValueAt(TabelaDeDados.getSelectedRow(), 2) + "");
        txt_Priority.setText(TabelaDeDados.getValueAt(TabelaDeDados.getSelectedRow(), 3) + "");

        String process = txt_NameProcess.getText().trim();
        String arrivalTime = txt_ArrivalTime.getText().trim();
        String burstTime = txt_BurstTime.getText().trim();
        String priority = txt_Priority.getText().trim();

        // Corrigir essa parte do editar

        DefaultTableModel dtm = (DefaultTableModel) TabelaDeDados.getModel();
        dtm.addRow(new String[]{process, arrivalTime, burstTime, priority});

        txt_NameProcess.requestFocus();
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInserirActionPerformed
        // TODO add your handling code here:

        String process = "P" + txt_NameProcess.getText().trim();
        String arrivalTime = txt_ArrivalTime.getText().trim();
        String burstTime = txt_BurstTime.getText().trim();
        String priority = txt_Priority.getText().trim();

        DefaultTableModel dtm = (DefaultTableModel) TabelaDeDados.getModel();
        dtm.addRow(new String[]{process,arrivalTime, burstTime, priority});

        txt_NameProcess.setText("");
        txt_ArrivalTime.setText("");
        txt_BurstTime.setText("");
        txt_Priority.setText("");

        txt_NameProcess.requestFocus();
    }//GEN-LAST:event_BtInserirActionPerformed

    private void txt_BurstTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BurstTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BurstTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabelaDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabelaDeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAvancar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtInserir;
    public javax.swing.JTable TabelaDeDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ArrivalTime;
    private javax.swing.JLabel lbl_BurstTime;
    private javax.swing.JLabel lbl_NameProcess;
    private javax.swing.JLabel lbl_Priority;
    private javax.swing.JTextField txt_ArrivalTime;
    private javax.swing.JTextField txt_BurstTime;
    private javax.swing.JTextField txt_NameProcess;
    private javax.swing.JTextField txt_Priority;
    // End of variables declaration//GEN-END:variables
}
